import Header from "./components/header/Header";
import "./globals.scss";
import { Inter } from "next/font/google";
import { PortfolioProvider } from "./hooks/context/portfolioContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PortfolioProvider>
          <Header />
          {children}
        </PortfolioProvider>
      </body>
    </html>
  );
}
